version: "3.8"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=./app/app.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
